<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ0Jt6Wq\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ0Jt6Wq/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQ0Jt6Wq.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQ0Jt6Wq\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQ0Jt6Wq\appAppKernelProdContainer([
    'container.build_hash' => 'Q0Jt6Wq',
    'container.build_id' => '849f887a',
    'container.build_time' => 1727835228,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ0Jt6Wq');
