<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1cIGlLn\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1cIGlLn/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1cIGlLn.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container1cIGlLn\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container1cIGlLn\appAppKernelDevDebugContainer([
    'container.build_hash' => '1cIGlLn',
    'container.build_id' => '1505158f',
    'container.build_time' => 1727834411,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1cIGlLn');
